"""Test Auto

Revision ID: d02388109f72
Revises: 2ac65e6a99d5
Create Date: 2024-03-19 10:39:18.378455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02388109f72'
down_revision: Union[str, None] = '2ac65e6a99d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
