"""Description of changes

Revision ID: f5996e453cb4
Revises: d02388109f72
Create Date: 2024-03-19 15:33:14.583354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5996e453cb4'
down_revision: Union[str, None] = 'd02388109f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
